source 'http://rubygems.org'
gem 'jekyll',     '=0.12.0'
gem 'liquid',     '=2.4.1'
gem 'redcarpet',  '=2.1.1'
gem 'maruku',     '=0.6.0'
gem 'rdiscount',  '=1.6.8'
gem 'RedCloth',   '=4.2.9'
gem 'compass'
gem 'compass_twitter_bootstrap', :git => 'https://github.com/vwall/compass-twitter-bootstrap.git'
